version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "mercado-solidario"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mercado-solidario-network
  adminer:
    image: adminer:standalone
    depends_on:
      - mysql
    ports:
      - 8081:8080
    networks:
      - mercado-solidario-network

volumes:
  data:
    name: "mercado-solidario-volume"

networks:
  mercado-solidario-network:
    driver: bridge
