version: "3.9"

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    networks:
      - mercado-solidario-network
  
  mercado-solidario-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - mercado-solidario-network  

volumes:
  data:
    name: "mercado-solidario-volume"

networks:
  mercado-solidario-network:
    driver: bridge
